apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-bclq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-bclq@sha256:ea4c45e1f9e5d69176418987c131f2e9d4c2697c84a266227c8088365b66ea9e
        name: my-nodejs
        resources: {}
status: {}
